# Writes DraftTable.lean from results/placement_8x8.tsv: the P0 hands with
# which P0 wins the placement game, in each of the two variants.
import os
HERE = os.path.dirname(os.path.abspath(__file__))
import sys
rows = [l.rstrip("\n").split("\t") for l in open(os.path.join(HERE, "..", "..", "results", "placement_8x8.tsv"))
        if not l.startswith("#") and not l.startswith("first_hand")]
w0 = [r[0] for r in rows if r[4] == "P0"]   # winner_P0_places_first
w1 = [r[0] for r in rows if r[5] == "P0"]   # winner_P1_places_first
def lst(xs): return "[" + ",\n  ".join(", ".join(f'"{x}"' for x in xs[i:i+8]) for i in range(0, len(xs), 8)) + "]"
with open(os.path.join(HERE, "DraftTable.lean"), "w") as f:
    f.write("/-! Generated by gen_table.py from results/placement_8x8.tsv: the hands of P0\n")
    f.write("with which P0 wins the placement game (draws and P1 wins are not listed). -/\n\n")
    f.write("namespace DraftTable\n\n")
    f.write(f"/-- P0 places first: the {len(w0)} winning hands of P0. -/\n")
    f.write(f"def winsP0PlacesFirst : List String :=\n  {lst(w0)}\n\n")
    f.write(f"/-- P1 places first: the {len(w1)} winning hands of P0. -/\n")
    f.write(f"def winsP1PlacesFirst : List String :=\n  {lst(w1)}\n\n")
    f.write("end DraftTable\n")
print(len(w0), len(w1))
